# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTests():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_creardirector(self, director):
    self.driver.get("http://localhost:8001/")
    self.driver.find_element(By.ID, ":r1:-tab-1").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\3Ar1\\3A-tabpanel-1 path").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys(director)
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
  
  def test_crearpelcula(self, title, description, year, director):
    self.driver.get("http://localhost:8001/")
    self.driver.find_element(By.CSS_SELECTOR, "#\\3Ar1\\3A-tabpanel-0 path").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys(title)
    self.driver.find_element(By.ID, "description").send_keys(description)
    self.driver.find_element(By.ID, "year").send_keys(year)
    self.driver.find_element(By.ID, "director_id").click()
    dropdown = self.driver.find_element(By.ID, "director_id")
    dropdown.find_element(By.XPATH, "//option[. = '" + director + "']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
  
test = TestTests()
test.setup_method()

# Agregar 2 directores
test.test_creardirector("Christopher Nolan")
test.test_creardirector("James Gunn")

# Agregar 1 película para cada uno de los directores
test.test_crearpelcula("Oppenheimer", "Description", "2023", "Christopher Nolan")
test.test_crearpelcula("Guardianes de la galaxia", "Description", "2014", "James Gunn")

# Agregar 2 películas más al director Cristopher Nolan
test.test_crearpelcula("Interestelar", "Description", "2014", "Christopher Nolan")
test.test_crearpelcula("El origen", "Description", "2010", "Christopher Nolan")